.PHONY: clean All

All:
	@echo "----------Building project:[ backdoor - Debug ]----------"
	@cd "backdoor" && "$(MAKE)" -f  "backdoor.mk"
clean:
	@echo "----------Cleaning project:[ backdoor - Debug ]----------"
	@cd "backdoor" && "$(MAKE)" -f  "backdoor.mk" clean
